version: "3" # optional since v1.27.0
services:
  sm_server:
    build: .
    ports:
      - "2350:2350/tcp"
      - "2350:2350/udp"
      - "3450:3450/tcp"
      - "3450:3450/udp"
      - "5000:5000"
    environment:
      - SERVER_NAME="A Maniaplanet Server"
      - DEDICATED_SERVER_ACCOUNT=${DEDICATED_SERVER_ACCOUNT}
      - DEDICATED_SERVER_ACCOUNT_PASSWORD=${DEDICATED_SERVER_ACCOUNT_PASSWORD}
      - GAME_MODE=ELITE
      - SERVER_MAX_PLAYERS=6
      - SERVER_PASSWORD=1596357
      - SERVER_MAX_SPECTATORS=15
